language: python
sudo: false
cache: pip
python:
  - "3.5"
env:
  - REQ="Django>1.10,<1.11"
install:
  - pip install -U pip wheel
  - pip install $REQ https://github.com/matthiask/django-mooch/archive/master.zip
  - python setup.py install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
